# Generated by Django 4.1.7 on 2023-04-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_username', models.CharField(max_length=100)),
                ('ad_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('cartproduct_username', models.CharField(blank=True, max_length=50, null=True)),
                ('cartproduct_name', models.CharField(max_length=50)),
                ('cartproduct_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('cartproduct_price', models.IntegerField()),
                ('cartproduct_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('category_description', models.CharField(max_length=500)),
                ('category_image', models.ImageField(upload_to='')),
                ('category_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone', models.IntegerField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('USER', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postcode', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('payment_type', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wishedlist',
            fields=[
                ('wishedlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('wishedlist_username', models.CharField(blank=True, max_length=50, null=True)),
                ('wishedlist_name', models.CharField(max_length=50)),
                ('wishedlist_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('wishedlist_price', models.IntegerField(blank=True, null=True)),
                ('wishedlist_quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=500)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_price', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shopyapp.category')),
            ],
        ),
    ]
