# Generated by Django 4.1.7 on 2023-04-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopyapp', '0003_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
