# Generated by Django 4.1.7 on 2023-04-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopyapp', '0004_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartproduct_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartproduct_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartproduct_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
