# Generated by Django 4.1.7 on 2023-04-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopyapp', '0005_alter_cart_cartproduct_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
    ]
