# Generated by Django 4.1.7 on 2023-04-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopyapp', '0007_alter_cart_cartproduct_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartproduct_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartproduct_quantity',
            field=models.IntegerField(),
        ),
    ]
