# Generated by Django 4.1.7 on 2023-04-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopyapp', '0008_alter_cart_cartproduct_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartproduct_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
