# Generated by Django 4.1.7 on 2023-04-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopyapp', '0012_alter_cart_cartproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartproduct_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartproduct_username',
            field=models.CharField(max_length=50),
        ),
    ]
