# Generated by Django 4.1.7 on 2023-04-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopyapp', '0013_alter_cart_cartproduct_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartproduct_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartproduct_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartproduct_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartproduct_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
