# Generated by Django 4.1.7 on 2023-04-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopyapp', '0014_alter_cart_cartproduct_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishedlist',
            name='wishedlist_image',
            field=models.ImageField(blank=True, default=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wishedlist',
            name='wishedlist_name',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='wishedlist',
            name='wishedlist_price',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='wishedlist',
            name='wishedlist_quantity',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='wishedlist',
            name='wishedlist_username',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
