# Generated by Django 4.1.7 on 2023-04-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopyapp', '0015_alter_wishedlist_wishedlist_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartproduct_image',
            field=models.ImageField(blank=True, default=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartproduct_name',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartproduct_price',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartproduct_quantity',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartproduct_username',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
