# Generated by Django 4.1.7 on 2023-04-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopyapp', '0019_alter_wishedlist_wishedlist_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishedlist',
            name='wishedlist_quantity',
        ),
    ]
